name: Deploy to Vercel

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "DRIVE_FOLDER_ID=${{ secrets.DRIVE_FOLDER_ID }}" >> .env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env

      - name: Create credentials folder
        run: mkdir -p src/credentials

      - name: Create credentials.json
        run: |
          cat <<EOF > src/credentials/credentials.json
          {
            "web": {
                "clientId": "${{ secrets.CLIENT_ID }}",
                "project_id": "formapp-386422",
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token",
                "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                "client_secret": "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",
                "redirect_uris": [
                    "http://localhost:3000/google/callback"
                ],
                "javascript_origins": [
                    "http://localhost:3000",
                    "http://localhost:5500"
                ]
            }
          }
          EOF

      - name: Create gmail-credentials.json
        run: |
          cat <<EOF > src/credentials/gmail-credentials.json
          {
            "type": "service_account",
            "project_id": "formapp-386422",
            "private_key_id": "${{secrets.GMAIL_PRIVATE_KEY_ID}}",
            "private_key": "${{secrets.GMAIL_PRIVATE_KEY}}",
            "client_email": "gmail-589@formapp-386422.iam.gserviceaccount.com",
            "client_id": "101381363474106410627",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/gmail-589%40formapp-386422.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
          }
          EOF
          
      - name: Create googledrive.json
        run: |
          cat <<EOF > src/credentials/googledrive.json
          {
            "type": "service_account",
            "project_id": "formapp-386422",
            "private_key_id": "${{secrets.GDRIVE_PRIVATE_KEY_ID}}",
            "private_key": "${{secrets.GDRIVE_PRIVATE_KEY}}",
            "client_email": "gmail-589@formapp-386422.iam.gserviceaccount.com",
            "client_id": "101381363474106410627",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/gmail-589%40formapp-386422.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
          }
          EOF

       

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build  # Certifique-se de que existe um script de build no seu package.json

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel@latest
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
